"""Initial migration - inventory and event_log tables

Revision ID: 54a046e80d47
Revises: 
Create Date: 2025-12-25 20:06:13.555322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a046e80d47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create inventory table
    op.create_table(
        'inventory',
        sa.Column('product_id', sa.String(), nullable=False),
        sa.Column('total_quantity', sa.Integer(), nullable=False),
        sa.Column('reserved_quantity', sa.Integer(), nullable=False),
        sa.Column('minimum_stock_level', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)

    # Create event_log table
    op.create_table(
        'event_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('product_id', sa.String(), nullable=False),
        sa.Column('event_data', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_log_event_type'), 'event_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_log_product_id'), 'event_log', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_log_product_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_event_type'), table_name='event_log')
    op.drop_table('event_log')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
